version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    # Placeholder configuration
  mongo:
    image: mongo:6
    # Placeholder configuration
